services:
  - type: web
    name: zografia-ai
    runtime: static
    buildCommand: ""
    staticPublishPath: "."
    pullRequestPreviewsEnabled: false
    autoDeploy: true
    headers:
      - path: /sw.js
        name: Service-Worker-Allowed
        value: /
      - path: /sw.js
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /manifest.json
        name: Cache-Control
        value: no-cache
